runs:
  using: composite
  steps:
    - name: Get node version
      uses: ./.github/actions/get-node-version
      id: get-node-version

    - name: Get pnpm version
      id: get-pnpm-version
      shell: bash
      run: |
        set -x
        PNPM_VERSION=$(jq -r '.engines.pnpm' < package.json | sed -r 's/[>=]+//g')
        echo "value=${PNPM_VERSION}" >> "$GITHUB_OUTPUT"

    - uses: pnpm/action-setup@v2.2.4
      with:
        version: ${{ steps.get-pnpm-version.outputs.value }}

    - uses: actions/setup-node@v3
      with:
        node-version: ${{ steps.get-node-version.outputs.value }}
        cache: pnpm

    - name: Install dependencies
      shell: bash
      run: |
        set -x
        pnpm install --frozen-lockfile --ignore-scripts
