#!/bin/sh
set -e

PACKAGE_LOCK_REGEX="(^yarn\.lock)"
PACKAGES=("$(git diff --name-only HEAD@{1} HEAD | grep -E "$PACKAGE_LOCK_REGEX")")

if [[ $PACKAGES ]]; then
  echo "📦 $PACKAGES was changed. Running yarn install to update your dependencies..."
  yarn install
fi
