#!/bin/sh
set -e

GREEN='\033[0;32m'
BLUE='\033[1;34m'
RED='\033[0;31m'
NC='\033[0m' # No Color

echo -e "\n\n📣 ${BLUE}Annoucements${NC} 📣"
echo -e "${GREEN}- Please use NX Cloud for local development${NC}\n\n"

PACKAGE_LOCK_REGEX="(^yarn\.lock)"
PACKAGES=("$(git diff --name-only HEAD@{1} HEAD | grep -E "$PACKAGE_LOCK_REGEX")")

if [[ $PACKAGES ]]; then
  echo "📦 $PACKAGES was changed. Running yarn install to update your dependencies..."
  yarn install
fi
