#!/bin/sh
set -e

GREEN='\033[0;32m'
BLUE='\033[1;34m'
RED='\033[0;31m'
NO_COLOUR='\033[0m'

echo "\n\n📣 ${BLUE}Onyx Announcements${NO_COLOUR} 📣"
echo "${GREEN}- Find Onyx documentation at https://onyx.engineering.mnscorp.net/ ${NO_COLOUR}\n\n"

if git diff --name-only HEAD@{1} HEAD | grep --silent '^pnpm-lock\.yaml'; then
  echo "📦 pnpm-lock.yaml was changed."
  echo "Running pnpm install to update your dependencies..."
  pnpm install
fi
