#!/bin/sh

set -e

SYMBOL_PASS="\xE2\x9C\x94"
SYMBOL_FAIL="\xE2\x9D\x8C"

pnpm lint-staged

echo "Verifying lockfile..."
if ! pnpm install --frozen-lockfile > /dev/null; then
    echo "$SYMBOL_FAIL package.json does not correspond to pnpm-lock.yaml"
    exit 1
else
    echo "$SYMBOL_PASS Lockfile verified"
fi
