name: PR validation

on:
  pull_request:
    types: [ready_for_review, opened, synchronize, reopened]
    branches:
      - main

env:
  NODE_VERSION: '14.x'

jobs:
  build:
    name: PR validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      # - name: Secrets scanning
      #   uses: edplato/trufflehog-actions-scan@master
      #   with:
      #     scanArguments: '--regex -x=truffle-hog-exclude.txt'

      - name: Setup NodeJs ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: yarn

      - name: Install dependencies
        run: yarn

      - name: Unit tests
        run: yarn nx affected:test --codeCoverage --base=remotes/origin/main

      - name: Build plugin
        run: yarn nx build nx-playwright

      # - name: Check version
      #   run: |
      #     cd dist/packages/nx-playwright
      #     git fetch --tags
      #     VERSION=$(npm pkg get version | xargs)
      #     LATEST=$(git describe --tags $(git rev-list --tags --max-count=1))
      #     echo "Current version $VERSION"
      #     echo "Latest version is $LATEST"
      #     if [ "$VERSION" = "$LATEST" ]; then
      #       echo "Version $VERSION is already published"
      #       exit 1; 
      #     fi

      - name: e2e tests
        run: |
          NX_PLUGIN_DIR=$(pwd)
          cd ..
          ls -la
          echo "before creating workspace"
          npx create-nx-workspace --appName=test-app --style=@emotion/styled --name=test-nx --preset=next --nxCloud=false --interactive=false < /dev/null
          
          cd test-nx
          echo "remove test-app-e2e"
          yarn nx generate remove test-app-e2e
          yarn add @playwright/test@^1.19.1 -D
          echo "test-app-e2e removed"
          ls -la
          
          pwd
          LOCAL_TEST_WORKSPACE="$(pwd)"

          cd $NX_PLUGIN_DIR
          cd dist/packages/nx-playwright/
          yarn link
          cd $LOCAL_TEST_WORKSPACE
          yarn add @mands/nx-playwright -D
          yarn unlink "@mands/nx-playwright"
          yarn link "@mands/nx-playwright"
          cd -

          cd $LOCAL_TEST_WORKSPACE
          yarn nx generate @mands/nx-playwright:project test-app-e2e --project test-app
          yarn nx e2e test-app-e2e --skip-nx-cache

          cd $NX_PLUGIN_DIR 
