name: PR validation

on:
  pull_request:
    types: [ready_for_review, opened, synchronize, reopened]
    branches:
      - main

env:
  NODE_VERSION: '14.x'

jobs:
  build:
    name: PR validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Scan for secrets
        uses: edplato/trufflehog-actions-scan@master
        with:
          scanArguments: '--regex -x=truffle-hog-exclude.txt'

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: yarn

      - name: Install and verify dependencies
        run: yarn install --frozen-lockfile

      - name: Run linters
        run: yarn nx affected:lint --base=remotes/origin/main

      - name: Run unit tests
        run: yarn nx affected:test --codeCoverage --base=remotes/origin/main

      - name: Build plugin
        run: yarn nx build nx-playwright

      - name: Check version
        run: yarn ts-node ci/version-check

      - name: Test plugin generation
        run: |
          NX_WORKSPACE=test-nx
          NX_APP=test-app

          pushd ..
          echo "Create a new workspace to test with"
          yarn create nx-workspace \
            --name=$NX_WORKSPACE --appName=$NX_APP \
            --preset=next --style=@emotion/styled \
            --nxCloud=false --interactive=false < /dev/null

          pushd $NX_WORKSPACE
          echo "Remove autogenerated e2e app"
          yarn nx generate remove $NX_APP-e2e
          git \
            -c user.name="pr-bot" \
            -c user.email="pr-bot@mnscorp.net" \
            commit -am "Remove $NX_APP-e2e"
          popd
          popd

          echo "Test ./local-test.sh (with cleanup flag)"
          ./local-test.sh -w ../$NX_WORKSPACE -a $NX_APP -C
          test -z "$(git status --porcelain)"

          echo "Test ./local-test.sh (without cleanup flag) (also tests that cleanup succeeded above)"
          ./local-test.sh -w ../$NX_WORKSPACE -a $NX_APP
          [ -d ../$NX_WORKSPACE/apps/$NX_APP-e2e ]
