name: PR validation

on:
  pull_request:
    types: [ready_for_review, opened, synchronize, reopened]
    branches:
      - main

env:
  NODE_VERSION: '14.x'

jobs:
  build:
    name: PR validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Secrets scanning
        uses: edplato/trufflehog-actions-scan@master
        with:
          scanArguments: '--regex -x=truffle-hog-exclude.txt'

      - name: Setup NodeJs ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: yarn

      - name: Install dependencies
        run: yarn

      - name: Unit tests
        run: yarn nx affected:test --codeCoverage --base=remotes/origin/main

      - name: Build plugin
        run: yarn nx build nx-playwright

      - name: Check version
        run: yarn ts-node ci/version-check
          
      - name: E2E tests
        run: |
          NX_PLUGIN_DIR=$(pwd)
          cd ..
          yarn create nx-workspace --appName=test-app --style=@emotion/styled --name=test-nx --preset=next --nxCloud=false --interactive=false < /dev/null
          
          cd test-nx
          yarn nx generate remove test-app-e2e
          
          LOCAL_TEST_WORKSPACE="$(pwd)"

          cd $NX_PLUGIN_DIR
          cd dist/packages/nx-playwright/
          yarn link
          cd $LOCAL_TEST_WORKSPACE
          yarn add @mands/nx-playwright -D
          yarn link "@mands/nx-playwright"

          yarn nx generate @mands/nx-playwright:project test-app-e2e --project test-app
          yarn playwright install --with-deps
          yarn nx e2e test-app-e2e --skip-nx-cache
