name: PR validation


on:
  pull_request:
    types: [ready_for_review, opened, synchronize, reopened]
    branches:
      - main

env:
  NODE_VERSION: '14.x'

jobs:
  build:
    name: PR validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      # - name: Secrets scanning
      #   uses: edplato/trufflehog-actions-scan@master
      #   with:
      #     scanArguments: "--regex -x=truffle-hog-exclude.txt"

      - name: Setup NodeJs ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: yarn
          
      # - name: Install dependencies
      #   run: yarn

      # - name: Build plugin
      #   run: yarn nx build nx-playwright

      # - name: Check version
      #   run: |
      #     cd dist/packages/nx-playwright
      #     git fetch --tags
      #     VERSION=$(cat package.json | grep version | head -1 | awk -F: '{ print $2 }' | sed 's/[",]//g' | xargs)
      #     LATEST=$(git describe --tags $(git rev-list --tags --max-count=1))
      #     echo "Current version $VERSION"
      #     echo "Latest version is $LATEST"
      #     if [ "$VERSION" = "$LATEST" ]; then
      #       echo "Version $VERSION is already published"
      #       exit 1; 
      #     fi

      - name: e2e tests
        run: |
          NX_PLUGIN_DIR=$(pwd)
          cd ..
          npx create-nx-workspace --appName=test-app --style=emotion --interactive=false < /dev/null

          LOCAL_TEST_WORKSPACE="$(pwd)/../nx-repo"

          cd $NX_PLUGIN_DIR
          yarn nx build nx-playwright
          cd dist/packages/nx-playwright/
          yarn link
          cd $LOCAL_TEST_WORKSPACE
          yarn add @mands/nx-playwright -D
          yarn unlink "@mands/nx-playwright"
          yarn link "@mands/nx-playwright"
          cd -

          cd $LOCAL_TEST_WORKSPACE
          yarn nx generate @mands/nx-playwright:project test-app-e2e --project test-app
          yarn nx e2e test-app-e2e --skip-nx-cache

          cd $NX_PLUGIN_DIR 

