name: PR validation


on:
  pull_request:
    types: [ready_for_review, opened, synchronize, reopened]
    branches:
      - main

env:
  NODE_VERSION: '14.x'

jobs:
  build:
    name: PR validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Secrets scanning
        uses: edplato/trufflehog-actions-scan@master
        with:
          scanArguments: "--regex -x=truffle-hog-exclude.txt"

      - name: Setup NodeJs ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: yarn
          
      - name: Install dependencies
        run: yarn

      - name: Build plugin
        run: yarn nx build nx-playwright

      - name: Setup release
        run: |
          cd dist/packages/nx-playwright
          echo "scope=@mands" > .npmrc
          echo "@mands:registry=https://registry.npmjs.org/" >> .npmrc
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> .npmrc

      - name: Semantic release
        uses: cycjimmy/semantic-release-action@v3
        with:
          dry_run: true
          working_directory: dist/packages/nx-playwright
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}